<?php

namespace Database\Seeders;

use App\Models\OrderDevice;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderDeviceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        $orders = [
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 2',
                'client_observations' => 'Observaciones del cliente 2',
                'diagnostic' => 'Diagnóstico 2',
                'ceca_observations' => 'Observaciones CECA 2',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN654321',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ],
            [
                'model' => 'Modelo 1',
                'client_observations' => 'Observaciones del cliente 1',
                'diagnostic' => 'Diagnóstico 1',
                'ceca_observations' => 'Observaciones CECA 1',
                'status' => 'En proceso',
                'computer' => 0,
                'serial_number' => 'SN123456',
                'cg_brand_id' => 1,
                'order_id' => 3,
                'cg_kind_failure_id' => 1,
                'cg_kind_object_id' => 1,
                'ceca_repairs' => 1,
            ]
        ];
        foreach ($orders as $order){
            OrderDevice::create($order);
        }

    }
}
